export const CATEGORIES_INIT = 'CATEGORIES_INIT';
export const CATEGORIES_SET = 'CATEGORIES_SET';

export const CATEGORIES_ADD = 'CATEGORIES_ADD';
export const CATEGORIES_ADD_SUCCESS = 'CATEGORIES_ADD_SUCCESS';
export const CATEGORIES_ADD_FAIL = 'CATEGORIES_ADD_FAIL';
export const CATEGORIES_DELETE = 'CATEGORIES_DELETE';
export const CATEGORIES_DELETE_SUCCESS = 'CATEGORIES_DELETE_SUCCESS';
export const CATEGORIES_EDIT = 'CATEGORIES_EDIT';
export const CATEGORIES_EDIT_SUCCESS = 'CATEGORIES_EDIT_SUCCESS';

export const ARTICLES_SET = 'ARTICLES_SET';
export const ARTICLES_INIT = 'ARTICLES_INIT';
export const ARTICLES_GET_CONTENT = 'ARTICLES_GET_CONTENT';
export const ARTICLES_SET_CONTENT = 'ARTICLES_SET_CONTENT';
export const ARTICLES_ADD = 'ARTICLES_ADD';
export const ARTICLES_ADD_SUCCESS = 'ARTICLES_ADD_SUCCESS';
export const ARTICLES_ADD_FAIL = 'ARTICLES_ADD_FAIL';
export const ARTICLES_DELETE = 'ARTICLES_DELETE';
export const ARTICLES_DELETE_SUCCESS = 'ARTICLES_DELETE_SUCCESS';
export const ARTICLES_EDIT = 'ARTICLES_EDIT';
export const ARTICLES_EDIT_SUCCESS = 'ARTICLES_EDIT_SUCCESS';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITITATE_LOGOUT = 'AUTH_INITITATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
