export const CATEGORIES_INIT = 'CATEGORIES_INIT';
export const CATEGORIES_SET = 'CATEGORIES_SET';

export const CATEGORIES_ADD = 'CATEGORIES_ADD';
export const CATEGORIES_ADD_SUCCESS = 'CATEGORIES_ADD_SUCCESS';
export const CATEGORIES_ADD_FAIL = 'CATEGORIES_ADD_FAIL';
export const CATEGORIES_EDIT = 'CATEGORIES_EDIT';
export const CATEGORIES_EDIT_INIT = 'CATEGORIES_EDIT_INIT';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITITATE_LOGOUT = 'AUTH_INITITATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
